name: SFTP Sync

on:
  push:
    branches:
      - main  # Of een andere branch die jij wil

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Delete and recreate /ROOT on server
      run: |
        lftp -u "${{ secrets.SSH_USER }}:${{ secrets.SSH_PASS }}" sftp://$SSH_HOST:$SFTP_PORT -e "
          set sftp:auto-confirm yes;
          set sftp:connect-program 'ssh -o StrictHostKeyChecking=no';
          rm -r /ROOT;
          mkdir /ROOT;
          bye
        "
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }} # Zorg ervoor dat hier 'david2%40davidnet.net' is
        SSH_PASS: ${{ secrets.SSH_PASS }}
        SFTP_PORT: '22'

    - name: Upload all repo files to /ROOT
      run: |
        lftp -u "${{ secrets.SSH_USER }}:${{ secrets.SSH_PASS }}" sftp://$SSH_HOST:$SFTP_PORT -e "
          set sftp:auto-confirm yes;
          set sftp:connect-program 'ssh -o StrictHostKeyChecking=no';
          mirror -R ./ /ROOT;
          bye
        "
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }} # Zorg ervoor dat hier 'david2%40davidnet.net' is
        SSH_PASS: ${{ secrets.SSH_PASS }}
        SFTP_PORT: '22'
